Application=99acres
Framework=Behave BDD
Module=New Launch
Base URL=https://www.99acres.com/
Browser=chrome
Headless=false
Location=Noida
Property Type=Flat/Apartment
Budget=20 Lacs - 80 Lacs
Bedroom=2 BHK